### ISSUE TITLE
antimicro.1

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#10]
https://github.com/juliagoda/antimicro/blob/f452fe31c359849b361ab75d3b5de00d366ef7ab/other/antimicro.1#L65

Should be:
````
Report dir bugs to antimicro home page: https://github.com/juliagoda/antimicro
````
;-)

**Comment by juliagoda** [comment]
Thank you for drawing attention to this line. I'll add an additional suffix ("/issues") too.
