### ISSUE TITLE
sudo apt show antimicro

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#11]
in terminal: `sudo apt show antimicro`
i dont know how to change:
![screenshot from 2018-04-27 09-00-38](https://user-images.githubusercontent.com/30092603/39363976-4220be92-49fa-11e8-8da2-2e8ee99d06e7.png)

**Comment by sirlucjan** [comment]
[code]apt-cache policy anitimicro[/code]

One important question:
How do you build antimicro? via make && sudo make install or via build a .deb package?
If via make && sudo make install , apt "doesn't see" yours antimicro and still show infos from ppa repository. You should build a own package.

**Comment by AdamKane41** [comment]
im building via "make" using master from juliagoda... i now purged everything related to antimicro from my machine, also removed old ppa from antimicro. and im about to rebuild with "make" using master from juliagoda...

did apt return info because i build and make "on top" of an old installation from old ppa?

**Comment by sirlucjan** [comment]
Please remove antimicro ppa from sources.list and try again "apt show antimicro". OK :)?

**Comment by AdamKane41** [comment]
80%....81%...

**Comment by AdamKane41** [comment]
**Unable to locate package antimicro**
nice! thank you! ;-D

**Comment by sirlucjan** [comment]
You're welcome.
