### ISSUE TITLE
Save New profile pop up after reboot

### ISSUE THREAD

**Issue by prog-amateur** [juliagoda/antimicro#28]
Hello, thank you for you kind support about this issue : 
I have made a profile, then saved it. I have also put is as "Default profile" and also ticked the "auto-load" option. However, when I reboot the programm or my computer, I have this pop-up `"Save profile changes ?`". 
Because despite the fact that I have saved my profile, the program load the "New profile" at start. 

How to solve this issue please ? Thank you very much for you help.

**Comment by juliagoda** [comment]
I understand. I will be fixing it from tomorrow.

**Comment by prog-amateur** [comment]
Thank you very much, please feel free to confirm when you succeed, and also to tell me how to fix it (to update, or compile new release from scratch). 
Just for information, I am on Ubuntu 18.04.

**Comment by juliagoda** [comment]
Is it ok now?

**Comment by prog-amateur** [comment]
@juliagoda Thank you for your help, but I don't know how to update your changes. 
I have tried to replace the files and start the `cmake .. make sudo make install` but I have error messages. I am sure I did it wrong. 
Please, could you tell me how to update, then I will do and feedback. Sorry for disturbing, and thank you very much.

**Comment by sirlucjan** [comment]
Paste logs with errors.

**Comment by prog-amateur** [comment]
I have downloaded the git into zip file, and have tried to compile again. 
Everything is OK until `sudo make install` : 
```
[100%] Built target antimicro
Install the project...
-- Install configuration: ""
-- Installing: /usr/bin/antimicro
-- Installing: /usr/share/pixmaps/antimicro.png
-- Installing: /usr/share/applications/antimicro.desktop
-- Installing: /usr/share/mime/packages/antimicro.xml
Scanning dependencies of target manpage
Built target manpage
Scanning dependencies of target appdata
/bin/sh: 1: itstool: not found
other/appdata/CMakeFiles/appdata.dir/build.make:57: recipe for target 'appdata' failed
make[4]: *** [appdata] Error 127
CMakeFiles/Makefile2:255: recipe for target 'other/appdata/CMakeFiles/appdata.dir/all' failed
make[3]: *** [other/appdata/CMakeFiles/appdata.dir/all] Error 2
CMakeFiles/Makefile2:262: recipe for target 'other/appdata/CMakeFiles/appdata.dir/rule' failed
make[2]: *** [other/appdata/CMakeFiles/appdata.dir/rule] Error 2
Makefile:216: recipe for target 'appdata' failed
make[1]: *** [appdata] Error 2
Scanning dependencies of target updateqm
Built target updateqm
-- Installing: /usr/share/man/man1/antimicro.1.gz
CMake Error at other/appdata/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/minitel/Documents/antimicro2/build/other/appdata/antimicro.appdata.xml".
Call Stack (most recent call first):
  other/cmake_install.cmake:46 (include)
  cmake_install.cmake:83 (include)


Makefile:117: recipe for target 'install' failed
make: *** [install] Error 1

```

**Comment by prog-amateur** [comment]
If you don't know how to help, at least, could you explain how to uninstall please ? Then I will try to recompile from scratch. Thank you

**Comment by sirlucjan** [comment]
```
itstool: not found
```
You should install itstool.

**Comment by juliagoda** [comment]
> If you don't know how to help, at least, could you ...

Ok, I've just read your message. It's not that I didn't know it because I wasn't even here. I was busy. I have my private life yet, people, so please calm down.

**Comment by prog-amateur** [comment]
>  I have my private life yet, people, so please calm down.
I think it is a misunderstanding (I think due to translation), so sorry please don't take it personal. I mean (not in an aggressive way) : if you don't know how to solve this issue, maybe I can try to remove Antimicro (and please tell me how to do that), then I will reinstall from scratch. Then maybe it will work. 

@sirlucjan : I will install itstool and feedback 

Thank you both

**Comment by juliagoda** [comment]
Does the problem disappear, when you uncheck first row labeled "Active" in Auto Profile option in Settings? I have noticed that it has something to do with AutoProfileWatcher, because when the row is checked and the tray icon is right-clicked, you can notice the moment, when it's changing to "<New>" profile. Is it true in your case too?

**Comment by juliagoda** [comment]
As I can see now it's even logical, because when you don't set default profile (editing it) for the first row, the program thinks that empty item in column named "Profile" means using of new profile. But I am not sure, if it's the same behaviour in your case.

**Comment by prog-amateur** [comment]
> Does the problem disappear, when you uncheck first row in "Active" column in Auto Profile option in Settings? Or when you **choose the first row** -> **click on "Edit" button** -> **Choose your default profile from your system** -> and **check** finally the row **as "Active"**?
> I have noticed that it has something to do with AutoProfileWatcher, because when the row is checked, the profile is not edited in the first row and the tray icon is right-clicked, you can notice the moment, when it's changing to "New" profile. Is it all true in your case too?

So I have just tried these steps without success. Does it work on your computer ? 

> As I can see now it's even logical, because when you don't set default profile (editing it) for the first row, the program thinks that empty item in column named "Profile" means using of new profile. But I am not sure, if it's the same behaviour in your case.

Yes, in my case, I can't even delete the first row. Just impossible, no matter what I do, this one, is on Default with no program for it. I have succeed anyway to add other default profiles for gnome-terminal-server (used for emulationstation), but no matter I make it active or not, no matter the order, this does not change. 
However, I have noticed something : when I open Antimicro, I have the popup message in the dialbox, and I have **another window** saying that no joystick has been found, and that I should update the devices. When I try to update, the program crashes. 

It seems to be a complex issue ^^

**Comment by juliagoda** [comment]
> So I have just tried these steps without success. Does it work on your computer ?

Yes, it works on my computer. Those problems appear only when I have a checked first row and when it's not edited (item for "Profile" column is empty). Btw you can't delete the first row, that's the way it was created by somebody earlier. You can just uncheck the option in the first row, because autoload of last profile works anyway (of course when checked in settings). Could you again make "git pull" to add new changes to your local files and rebuild it? It's strange because I don't have any of those problems anymore.

**Comment by juliagoda** [comment]
Well, on another system it's the same. It's just like in my case. 

![2018-10-10-000909_1366x768_scrot](https://user-images.githubusercontent.com/24532426/46702155-60376e80-cc22-11e8-9e1b-058eccdf4866.png)

**Comment by prog-amateur** [comment]
So, I have git clone your files and build them again (git pull does nothing in my side) 

In my case I have kept the settings like this : 
![20-43-07](https://user-images.githubusercontent.com/33793118/46759722-5f5d1600-ccd0-11e8-816e-de6d43d9766c.png)

Then I have tested many scenarios : 
![20-43-24](https://user-images.githubusercontent.com/33793118/46759792-874c7980-ccd0-11e8-91b3-6735475e4691.png)
![20-43-40](https://user-images.githubusercontent.com/33793118/46759794-89163d00-ccd0-11e8-83a1-7c322a1a4414.png)
![20-43-51](https://user-images.githubusercontent.com/33793118/46759799-8b789700-ccd0-11e8-9d1c-4bdcfd82ca4c.png)

However, each time (after each change) I close, then re-open AntiMicro, I have this : 
![20-42-03](https://user-images.githubusercontent.com/33793118/46759820-9a5f4980-ccd0-11e8-8adf-b13cf9ee3bd4.png)

**Comment by juliagoda** [comment]
> git pull does nothing in my side

1. Do you use my version from last commit from master branch? (git clone -b master https://github.com/juliagoda/antimicro.git)
2. Do you use at least Qt5 with version greater or equal to 5.10? If not, I can help you with that.

If anyone else has the same problem, feel free to let me know here

**Comment by prog-amateur** [comment]
Hello, I am sorry, I did not have time to test. It is possible that I don't use the last commit (because I have just used `git clone https://github.com/juliagoda/antimicro.git`) I will try to confirm as soon as possible.

**Comment by juliagoda** [comment]
git clone [link] is equal to git clone -b master [link], because the default branch on this site is master. I hope that this time I've found a real solution (emitting of propertyUpdated() signals too many times) , not temporary (using of disconnectCheckUnsavedEvent() and reconnectCheckUnsavedEvent() in JoyTabWidget::loadSetting method)

**Comment by AdamKane41** [comment]
last version of antimicro from juliagoda repo also gave me the pop up window on antimicro open and quit..looked like this:
![screenshot from 2018-10-15 10-29-45](https://user-images.githubusercontent.com/30092603/46960047-93875c80-d06b-11e8-9b59-e67ed64dbce5.png)

but now with latest master from juliagoda (october 15) this anoying window no longer pop ups on antimicro open and quit.

I consider this issue fixed on my machine now. thanks
peace!

**Comment by juliagoda** [comment]
Thanks for your response

**Comment by prog-amateur** [comment]
This is a knightmare. I still have the issue. I have also installed QT 5.11.2 but when I do qmake -v, it gives me Qt version 4 (strange). 
In any case, please do you know how to uninstall everything ? I am sure I did something wrong, so I would like to reinstall everything from scratch properly. 
Thank you very much
