### ISSUE TITLE
Screenshots updates

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#3]
Light:
![screenshot from 2018-04-09 15-59-09](https://user-images.githubusercontent.com/30092603/38522284-160964b8-3c16-11e8-811c-2b74907e2b2e.png)
![screenshot from 2018-04-09 17-00-00](https://user-images.githubusercontent.com/30092603/38522851-d7e59ef2-3c17-11e8-91f1-1ceb6bd2ddcc.png)
![screenshot from 2018-04-09 16-59-41](https://user-images.githubusercontent.com/30092603/38522860-de47408e-3c17-11e8-8fa4-0995e364ed42.png)

Dark:
![screenshot from 2018-04-09 16-46-43](https://user-images.githubusercontent.com/30092603/38522307-273c2108-3c16-11e8-816a-2f970045cc64.png)
![screenshot from 2018-04-09 16-52-02](https://user-images.githubusercontent.com/30092603/38522824-c0ab15aa-3c17-11e8-8789-620e6fe24926.png)
![screenshot from 2018-04-09 16-56-16](https://user-images.githubusercontent.com/30092603/38522837-d05da436-3c17-11e8-8beb-caa34f9b0b53.png)

**Comment by juliagoda** [comment]
Thanks
