### ISSUE TITLE
left and right triggers presets

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#34]
in LEFT and RIGHT TRIGGERS sections in the PRESETS menu ther use to be a RIGHT CLICK and LEFT CLICK presets options but now they are gone... can we have them back?

![yyy](https://user-images.githubusercontent.com/30092603/46960676-11983300-d06d-11e8-9046-4f0ba53f1ea8.png)

peace

**Comment by AdamKane41** [comment]
old version was like this;
![7](https://user-images.githubusercontent.com/30092603/46961170-2a551880-d06e-11e8-804b-f5373ddcf90f.png)

**Comment by AdamKane41** [comment]
aaaaaaah i get it. left and right click presets are only available when set to "throttle" mode and not in "normal"

**Comment by juliagoda** [comment]
Yes, the program in some places works dynamically. Can I close the issue or is there some problem waiting  for fixing?

**Comment by AdamKane41** [comment]
this can be close, sorry about that

**Comment by juliagoda** [comment]
no problem
