### ISSUE TITLE
"Quick Set" button and other mapping buttons causing MIT-MAGIC-COOKIE-1 segmentation fault on Ubuntu 18.10.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [juliagoda/antimicro#39]
The profiles from antimicro (2016 version) are working fine with all the mapped buttons.
But when I try to chance the mapping to most of the buttons, by clicking on "Quick Set" or "A:" or "B:" and other buttons, antimicro crashes with this output in the terminal: "Invalid MIT-MAGIC-COOKIE-1 keySegmentation fault (core dumped)".
Buttons that are working as expected: L Trigger, R Trigger, L stick, R stick, Dpad.
Other buttons, for example: Controller Mapping, Properties and Key Checker, are working too.
Tested with the gamepad "Steelseries Stratus Xl" on Ubuntu 18.10 amd64.
I searched for some workarounds but found nothing that helped.

**Comment by juliagoda** [comment]
> The profiles from antimicro (2016 version) are working fine with all the mapped buttons.

So you are trying to import a profile that is 2-years old? If I understand correctly? If that's the case, then could you send me the profile file by email?

**Comment by juliagoda** [comment]
How is it working now? By the way I hope that you are not using sudo privileges during execution

**Comment by a-l-e-x-d-s-9** [comment]
It's working without crashing now (and I do not use "sudo" to execute), although it still prints the message "Invalid MIT-MAGIC-COOKIE-1 key" in the terminal.
Thank you!

**Comment by juliagoda** [comment]
I've found some sites with explanations:

[iwf1.com](https://iwf1.com/quick-fix-invalid-mit-magic-cookie-1-sudo)
[Slopjong.de](http://slopjong.de/2011/06/14/invalid-mit-magic-cookie-1-key/)
[Ubuntu forum](https://ubuntuforums.org/showthread.php?t=2392377)
[Linux Questions](https://www.linuxquestions.org/questions/debian-26/xlib-invalid-mit-magic-cookie-1-key-278821/)

Probably:
> Most of the resources you may encounter will advise you to simply delete the ~/.Xauthority file in home folder in order for the problem to disappear.

**Comment by a-l-e-x-d-s-9** [comment]
I've seen a few of these links before. But I don't execute the antimicro with "sudo", and there is no ".Xauthority" file in my home folder.
I followed the suggestions from [here](https://www.suse.com/c/how-get-graphical-applications-working-sudo-sle-10/) but it did nothing for me.
I think it's related to my DISPLAY being ":1" and not ":0". I have no idea why only the key mapping window is bothered by it.

**Comment by juliagoda** [comment]
the window is bothered by it because of the lines of code in src/keyboard/virtualkeyboardmousewidget.cpp:

```
Display *dpy = XOpenDisplay(":0"); // default display
if (dpy == nullptr) dpy = XOpenDisplay(X11Extras::getInstance()->getEnvVariable("DISPLAY")); // if default display is not :0, then find current display reading env variable from system - (echo $DISPLAY)
XKeyboardState x;
XGetKeyboardControl(dpy, &x);
XCloseDisplay(dpy);
return x.led_mask & 2;
```
I needed it to know, if numlock is activated or not for keyboard. I haven't found better solution for Linux so far. If you really want to know the reason, you can change ":0" to ":1" and compile it again.

**Comment by a-l-e-x-d-s-9** [comment]
I see. Unfortunately, I can't suggest a better solution. Thanks for solving the crashing!

**Comment by juliagoda** [comment]
but maybe the problem is related to first attempt with ":0" in the code, so I will remove the first line and you can see again, it it's still appearing

**Comment by a-l-e-x-d-s-9** [comment]
Yes, the latest commit works fine, without any warnings.
Keep up the good work!
