### ISSUE TITLE
Crash when dead zone = max zone

### ISSUE THREAD

**Issue by seally1186** [juliagoda/antimicro#45]
Hi,

If I set the dead zone to be == the max zone for a trigger, the program seems to crash.

It looks like the problem may be in joyaxis.cpp in getDistanceFromDeadZone. The cast to double is happening after the division, so a divide by zero would lead to an FPE. Casting only the numerator or denominator seems to fix it (though I don't know what value is returned in that case).

Thanks!

**Comment by juliagoda** [comment]
How is it working now?

**Comment by seally1186** [comment]
Works great, thanks!
