### ISSUE TITLE
Panel icon is unresponsive when autostarted with system

### ISSUE THREAD

**Issue by maxigaz** [juliagoda/antimicro#62]
When antimicro is set to be launched automatically at system start and there's a gamepad detected, the panel icon doesn't respond to left or right mouse clicks. I need to close it with `pkill antimicro` and run the program again to make it work.

Operating System: Manjaro Linux KDE
Antimicro Version: 2.24*
KDE Plasma Version: 5.15.2
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.1
Kernel Version: 4.19.28-1-MANJARO x86_64

*According to `antimicro -v`, the version number is 2.24. However, the [AUR package](https://aur.archlinux.org/packages/antimicro/) info says it's 2.24.1.

**Comment by juliagoda** [comment]
I will take a look at it and the rest from Monday. I've just moved into new apartment

**Comment by maxigaz** [comment]
Sure. Thank you very much for your work!

**Comment by juliagoda** [comment]
Could you check if this is still present in the last commit from the test branch after changes? 

```
git clone -b testing https://github.com/juliagoda/antimicro.git
cd antimicro
mkdir compile
cd compile
cmake ..
make
sudo make install
```

**Comment by maxigaz** [comment]
This one is seems to be fixed now. Thank you very much!
