### ISSUE TITLE
New auto profiles cannot be added in the options

### ISSUE THREAD

**Issue by maxigaz** [juliagoda/antimicro#65]
When I go to Options → Settings → Auto Profile and add a new one, it won't show up in the list of auto profiles and it can't be used either.

The only way I can make it show up in the list is by editing what's under `[AutoProfiles]` in `~/.config/antimicro/antimicro_settings.ini`. Then, I can finetune its details in the settings using the Edit button normally.

* Operating System: Manjaro Linux KDE
* Antimicro Version: 2.24*
* Qt Version: 5.12.2
* Kernel Version: 4.19.32-1-MANJARO x86_64

*According to `antimicro -v`, the version number is 2.24. However, the [AUR package](https://aur.archlinux.org/packages/antimicro/) info says it's 2.24.1.

**Comment by juliagoda** [comment]
Could you check if this is still present in the last commit from the test branch? 

```
git clone -b testing https://github.com/juliagoda/antimicro.git
cd antimicro
mkdir compile
cd compile
cmake ..
make
sudo make install
```

**Comment by maxigaz** [comment]
I've just tried compiling it with your instructions. New items still don't show up in the list.

**Comment by juliagoda** [comment]
Have you compiled with WITH_X11 or WITH_UINPUT option? Have you tried to remove/rename settings file in "~/.config/antimicro" ?

**Comment by maxigaz** [comment]
> Have you compiled with WITH_X11 or WITH_UINPUT option?

No, I just did exactly what you wrote [above](https://github.com/juliagoda/antimicro/issues/65#issuecomment-486388885).

> Have you tried to remove/rename settings file in "~/.config/antimicro" ?

I've just tried it for the first time, and it seems to be working now. Thanks a lot!
