### ISSUE TITLE
AntiMicro freezes when unbinding a button

### ISSUE THREAD

**Issue by Sixdd6** [juliagoda/antimicro#75]
edit: I just realized this project is abandoned, I'll leave this here in case someone else picks it up.
 --- 
I have a profile saved but when I try to unbind a button from that profile the whole app just locks up and I have to kill it manually.

OS: Manjaro Linux
Version: 2.24.2 from AUR

**Comment by juliagoda** [comment]
#74

**Comment by juliagoda** [comment]
#74

**Comment by juliagoda** [comment]
Does project from last commit work properly? Does the error still appear?
