### ISSUE TITLE
Include mention of new dependency extra-cmake-modules

### ISSUE THREAD

**Issue by keianrao** [juliagoda/antimicro#80]
Hello,

The latest releases of this repo's antimicro needs `extra-cmake-modules` - which isn't listed in the Readme yet.

The Debian package for it is `extra-cmake-modules` (another package, `libecm-dev`, throws in a lot of confusion). It seems to have the same name in AUR for Arch.

Also, thank you for working on this project.

**Comment by juliagoda** [comment]
Is `libecm-dev` also necessary on Debian?

**Comment by keianrao** [comment]
Hello,

Sorry for the late reply!

`libecm-dev` isn't needed - it's the development headers for `gmp-ecm`, which is a very different library.

Just `extra-cmake-modules` will do - it's a package meant for development, so there's no `-dev` suffix for it.

Thanks again

**Comment by juliagoda** [comment]
Ok, everything is clear now
