### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#9]
Your fork of antimicro is the absolute best. It runs great on Ubuntu 18.04. The compiling & make & install is near **perfection** . Thank you!
I changed the following on my copy (to have a ubuntu flavor), feel free to add them or not.. peace!

In my **antimicro/src/images/** I did this: caba2cb489c80da8b32a23f5489075c177038d9c 

So the tray icon and taskbar icon are not the same.

![000](https://user-images.githubusercontent.com/30092603/38775303-da089cc8-404c-11e8-8476-2a83ceb22712.png)
![0002](https://user-images.githubusercontent.com/30092603/38775305-df521ed4-404c-11e8-9d64-cb9d9c876b85.png)

And:
 
![peek 2018-04-15 01-15](https://user-images.githubusercontent.com/30092603/38775272-1fdd161c-404c-11e8-80bf-8ee7fa951b01.gif)

;-D

**Comment by juliagoda** [comment]
Thank you for your help and advices. I think that, what you created is nice and I'll take it soon to the project
